backend:
  name: git-gateway
  branch: main

media_folder: ""
public_folder: "/"

collections:
  - name: "events"
    label: "Мероприятия"
    folder: "content/events"
    create: true

    fields:
      - {label: "Название", name: "title", widget: "string"}
      - {label: "Описание", name: "body", widget: "markdown"}
      - {label: "Фото", name: "image", widget: "image"}

  - name: "gallery"
    label: "Фото"

    folder: "content/gallery"
    create: true

    fields:
      - {label: "Фото", name: "image", widget: "image"}
